export default [
  {
    id: 1,
    description:
      'Bugün harika bir gün geçirdim! Sabah erkenden kalkıp doğanın tadını çıkardım. Güneş ışığı, kuş cıvıltıları ve temiz hava ruhuma iyi geldi. Sonrasında güzel bir kahve içip kitap okudum. Öğleden sonra arkadaşlarımla sahilde yürüyüş yaptık. Mutluluk verici bir gündü!',
    date: '2024-06-02 11:00:00',
    likes: 150,
    comments: 30,
    image: 'https://picsum.photos/1080/607?random=1',
    user: {
      name: 'Murat Yılmaz',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
  },
  {
    id: 2,
    description:
      'Bugün uzun zamandır planladığım doğa yürüyüşünü gerçekleştirdim. Sabah erkenden yola çıktım ve muhteşem bir manzarayla karşılaştım. Kuş sesleri, hafif rüzgar ve yeşillikler arasında yürümek inanılmaz keyifliydi. Gün batımını izlemek ise günün en güzel anlarından biriydi!',
    date: '2024-06-03 14:30:00',
    likes: 220,
    comments: 45,
    image: 'https://picsum.photos/1080/607?random=2',
    user: {
      name: 'Elif Karaca',
      avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    },
  },
  {
    id: 3,
    description:
      'Bugün harika bir kahvaltıyla güne başladım. Sonrasında sahile gidip yürüyüş yaptım. Deniz havası almak ruhuma çok iyi geldi. Biraz müzik dinleyip kitap okudum. Akşam arkadaşlarla buluşup güzel bir yemek yedik. Günümü dolu dolu geçirdiğim için çok mutluyum!',
    date: '2024-06-04 09:15:00',
    likes: 310,
    comments: 65,
    image: 'https://picsum.photos/1080/607?random=3',
    user: {
      name: 'Ahmet Demir',
      avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
  },
  {
    id: 4,
    description:
      'Bugün yepyeni bir deneyim yaşadım! Daha önce hiç denemediğim bir sporu yapmaya karar verdim ve oldukça keyif aldım. Başlangıçta zorlanmış olsam da zamanla alıştım. Yeni şeyler keşfetmek ve kendimi geliştirmek bana her zaman büyük bir motivasyon sağlıyor!',
    date: '2024-06-05 18:45:00',
    likes: 180,
    comments: 50,
    image: 'https://picsum.photos/1080/607?random=4',
    user: {
      name: 'Zeynep Kaya',
      avatar: 'https://randomuser.me/api/portraits/women/11.jpg',
    },
  },
  {
    id: 5,
    description:
      'Bugün kendime vakit ayırıp güzel bir film izledim. Film beni düşündürdü ve ilham verdi. Sonrasında en sevdiğim kafeye gidip kahvemi yudumladım. Dışarıda oturup insanları izlemek, doğanın güzelliğini fark etmek huzur vericiydi. Böyle anlar insanın ruhunu besliyor.',
    date: '2024-06-06 12:10:00',
    likes: 275,
    comments: 75,
    image: 'https://picsum.photos/1080/607?random=5',
    user: {
      name: 'Emre Şahin',
      avatar: 'https://randomuser.me/api/portraits/men/5.jpg',
    },
  },
  {
    id: 6,
    description: 'Güzel anılar biriktirmek paha biçilemez.',
    date: '2024-06-07 07:30:00',
    likes: 195,
    comments: 40,
    image: 'https://picsum.photos/1080/607?random=6',
    user: {
      name: 'Fatma Çelik',
      avatar: 'https://randomuser.me/api/portraits/women/6.jpg',
    },
  },
  {
    id: 7,
    description: 'Kahve ve kitap ile mükemmel bir gün.',
    date: '2024-06-08 21:15:00',
    likes: 260,
    comments: 55,
    image: 'https://picsum.photos/1080/607?random=7',
    user: {
      name: 'Mehmet Özkan',
      avatar: 'https://randomuser.me/api/portraits/men/7.jpg',
    },
  },
  {
    id: 8,
    description: 'Bugün harika bir doğa yürüyüşü yaptım.',
    date: '2024-06-09 13:25:00',
    likes: 350,
    comments: 90,
    image: 'https://picsum.photos/1080/607?random=8',
    user: {
      name: 'Selin Aydın',
      avatar: 'https://randomuser.me/api/portraits/women/8.jpg',
    },
  },
  {
    id: 9,
    description: 'Müziğin ritmiyle enerji doluyorum!',
    date: '2024-06-10 16:40:00',
    likes: 200,
    comments: 38,
    image: 'https://picsum.photos/1080/607?random=9',
    user: {
      name: 'Burak Koç',
      avatar: 'https://randomuser.me/api/portraits/men/9.jpg',
    },
  },
  {
    id: 10,
    description: 'Lezzetli bir yemek keyfi yaşadım.',
    date: '2024-06-11 11:55:00',
    likes: 330,
    comments: 82,
    image: 'https://picsum.photos/1080/607?random=10',
    user: {
      name: 'Ayşe Doğan',
      avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    },
  },
  {
    id: 11,
    description: 'Kendime vakit ayırmak çok önemli.',
    date: '2024-06-12 08:20:00',
    likes: 180,
    comments: 29,
    image: 'https://picsum.photos/1080/607?random=11',
    user: {
      name: 'Cem Yıldız',
      avatar: 'https://randomuser.me/api/portraits/men/11.jpg',
    },
  },
  {
    id: 12,
    description: 'Bugün harika bir sürprizle karşılaştım.',
    date: '2024-06-13 17:10:00',
    likes: 245,
    comments: 53,
    image: 'https://picsum.photos/1080/607?random=12',
    user: {
      name: 'Melisa Aksoy',
      avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    },
  },
  {
    id: 13,
    description: 'Doğanın sesi ruhuma huzur veriyor.',
    date: '2024-06-14 14:00:00',
    likes: 300,
    comments: 77,
    image: 'https://picsum.photos/1080/607?random=13',
    user: {
      name: 'Oğuz Kılıç',
      avatar: 'https://randomuser.me/api/portraits/men/13.jpg',
    },
  },
  {
    id: 14,
    description: 'Sanat galerisi gezmek ilham verici.',
    date: '2024-06-15 19:50:00',
    likes: 275,
    comments: 60,
    image: 'https://picsum.photos/1080/607?random=14',
    user: {
      name: 'Gizem Yalçın',
      avatar: 'https://randomuser.me/api/portraits/women/14.jpg',
    },
  },
  {
    id: 15,
    description: 'Gün batımını izlemek harika bir his!',
    date: '2024-06-16 09:45:00',
    likes: 165,
    comments: 34,
    image: 'https://picsum.photos/1080/607?random=15',
    user: {
      name: 'Efe Güneş',
      avatar: 'https://randomuser.me/api/portraits/men/15.jpg',
    },
  },
  {
    id: 16,
    description: 'Arkadaşlarla geçen keyifli bir gün.',
    date: '2024-06-17 23:05:00',
    likes: 210,
    comments: 47,
    image: 'https://picsum.photos/1080/607?random=16',
    user: {
      name: 'Deniz Kaplan',
      avatar: 'https://randomuser.me/api/portraits/women/16.jpg',
    },
  },
  {
    id: 17,
    description: 'Yeni bir hobiye başlamak çok güzel!',
    date: '2024-06-18 06:30:00',
    likes: 320,
    comments: 85,
    image: 'https://picsum.photos/1080/607?random=17',
    user: {
      name: 'Kerem Çetin',
      avatar: 'https://randomuser.me/api/portraits/men/17.jpg',
    },
  },
];
